# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'CAU_hashkeyword_IOS_application' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'

  # Pods for CAU_hashkeyword_IOS_application

end
