# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'CAU_Notification' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Messaging'

  # Pods for CAU_Notification

end
